flags: {}
extra-package-dbs: []
packages:
  - '.'
extra-deps:
  - Euterpea-2.0.7
  - PortMidi-0.2.0.0
  - arrows-0.4.4.2
  - Stream-0.4.7.2
  - lazysmallcheck-0.6
resolver: lts-17.9
compiler: ghc-8.10.7
nix:
  packages:
    - gcc
    - ncurses
